### ISSUE TITLE
Wrong width

### ISSUE THREAD

**Issue by maciogg** [PuzzleTakX/flutter_stepindicator#2]
Hi, nice plugin :)

I found error - when list contains 4 elements extra right padding is added.
For 3 & 5 elements is OK

<img width="636" alt="Zrzut ekranu 2023-12-10 o 21 45 45" src="https://github.com/PuzzleTakX/flutter_stepindicator/assets/26849468/f70b10cb-2d65-4685-80a6-63ab477601c9">
<img width="636" alt="Zrzut ekranu 2023-12-10 o 21 45 33" src="https://github.com/PuzzleTakX/flutter_stepindicator/assets/26849468/9b6fd47d-56a3-420f-9e25-805e43e1d9f3">
<img width="636" alt="Zrzut ekranu 2023-12-10 o 21 45 15" src="https://github.com/PuzzleTakX/flutter_stepindicator/assets/26849468/20805494-0001-41e6-a17a-5c13fbc6e8b3">

**Comment by PuzzleTakX** [comment]
thanks🙂, fixed a few bugs extensively
